# Generated by Django 4.2 on 2024-04-07 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('role', models.CharField(choices=[('Administrator', 'Administrator'), ('Client', 'Client'), ('User', 'User')], max_length=20, verbose_name='Role')),
                ('photo_url', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Profile Photo')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('email_verified', models.BooleanField(default=False, help_text='Set to true when the user have verified its email address.', verbose_name='verified')),
                ('terms_policy', models.BooleanField(default=False, help_text='Set to true when the user accepted conditions and policy.', verbose_name='Terms & Policy')),
                ('o_key', models.BinaryField(verbose_name='OTP key')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
